apiVersion: v1
kind: Service
metadata:
  labels:
    name: data-collect
  name: data-collect
  namespace: gridvo
spec:
  selector:
    name: data-collect
  ports:
     - port: 80
       targetPort: 3001
